---

- name: "configuration play." 
  hosts: web
  user: ec2-user
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python2
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python2 || (yum update -y && yum install -y python2)
      changed_when: false
    
    - setup:

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    # Add more env vars here

  roles:
    - minikube