version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myPassword
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  db-migrator:
    image: udacity-devops-capstone-dbmigrator
    build:
      context: .
      dockerfile: src/Udacity.DevOps.Capstone.DbMigrator/Dockerfile
    pull_policy: if_not_present
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=Capstone;User ID=postgres;Password=myPassword;
    depends_on:
      - db

  webapp:
    image: udacity-devops-capstone-blazor
    build:
      context: .
      dockerfile: src/Udacity.DevOps.Capstone.Blazor/Dockerfile
    pull_policy: if_not_present
    ports:
      - 8080:80
      - 8443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - App__SelfUrl=http://localhost:8080
      - App__RedirectAllowedUrls=http://localhost:8080
      - ConnectionStrings__Default=Host=db;Port=5432;Database=Capstone;User ID=postgres;Password=myPassword;
      - AuthServer__Authority=http://localhost:8080
    depends_on:
      db-migrator:
        condition: service_completed_successfully
    
volumes:
  db:
    external: false