---
- name: conf repo for kubectl
  become: true
  yum_repository:
    name: Kubernetes
    description: Kubectl
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes

- name: Installing kubectl
  become: true
  yum:
    name: kubectl
    state: present

- name: Installing docker
  become: true
  yum:
    name: docker
    state: present

- name: Installing conntrack
  become: true
  yum:
    name: conntrack
    state: present

- name: Downloading minikube
  become: true
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    dest: /root/minikube-latest.x86_64.rpm

- name: Installing minikube
  become: true
  yum:
    name: /root/minikube-latest.x86_64.rpm
    state: present

- name: Start docker daemon
  become: yes
  command: systemctl start docker

- name: Setup necessary permission for "{{ ansible_user }}"
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Starting minikube driver using docker
  command: minikube start --driver=docker

- name: Installing Nginx
  become: true
  command: amazon-linux-extras install nginx1.12 -y