Description: >
  Capstone backend stack.
Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Capstone-${ID}
      GroupDescription: Allow port 22 and port 8080.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      SubnetId: subnet-02dea923343ebff52
      SecurityGroupIds: !GetAtt InstanceSecurityGroup.GroupId
      KeyName: capstone 
      ImageId: ami-0fa1de1d60de6a97e
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}