Description: >
  Capstone backend stack.
Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Capstone-${ID}
      GroupDescription: Allow port 22 and port 80.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity 
      ImageId: ami-068663a3c619dd892
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}