Description: >
  Cloudfront distribution for Capstone.

Parameters:
  BackendOrigin:
    Description: Orgin of EC2 hosting Minikube
    Type: String
  
  WorkflowID:
    Description: CircleCI workflow ID.
    Type: String

Resources:
  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${BackendOrigin}"
            Id: webpage
            CustomOriginConfig:
              HTTPPort: 8080
              HTTPSPort: 8443
              OriginProtocolPolicy: match-viewer
        Enabled: True
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: CircleCI Workflow ID
    Export:
      Name: WorkflowID