Description: >
  Cloudfront distribution for Capstone.

Parameters:
  BackendOrigin:
    Description: Orgin of EC2 hosting Minikube
    Type: String
  
  WorkflowID:
    Description: CircleCI workflow ID.
    Type: String

Resources:
  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${BackendOrigin}"
            Id: webpage
            CustomOriginConfig:
              HTTPPort: 8080
              HTTPSPort: 8443
              OriginProtocolPolicy: match-viewer
        Enabled: True
        DefaultCacheBehavior:
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all
