---
- name: Apply Page Template
  vars:
    aspnet_env: "{{ lookup('env', 'ASPNETCORE_ENVIRONMENT')}}"
    aspnet_urls: "{{ lookup('env', 'ASPNETCORE_URLS')}}"
    url: "http://{{ lookup('env', 'CLOUDFRONT_ORIGIN')}}"
    connection_string: "{{ lookup('env', 'CONNECTIONSTRINGS__DEFAULT')}}"
  template:
    src: deployment.yml.j2
    dest: deployment.yml

- name: Create K8S Deployment
  shell: |
    kubectl apply -f deployment.yml

- name: Installing screen for port-forward
  become: true
  yum:
    name: screen
    state: present

- name: Port forward
  shell: screen -S kubectl port-forward deployment/udacity-devops-capstone-deployment --address 0.0.0.0 8080:80